language: java

services:
  - postgresql

before_script:
  - psql -c 'create database travis_ci_test;' -U postgres
  - touch local.properties
  - cp local.properties.travis local.properties

script:
  - gradle install
  - gradle test
