language: java

services:
  - postgresql

before_script:
  - psql -c 'create database travis_ci_test;' -U postgres
  - touch local.properties
  - cat > local.properties <<EOL
    postgreUser=postgres
    postgrePass=
    postgreUrl=jdbc:postgresql://localhost/travis_ci_test

    postgreTestUser=postgres
    postgreTestPass=
    postgreTestUrl=jdbc:postgresql://localhost/travis_ci_test
    EOL

script:
  - gradle install
  - gradle test
