language: java

services:
  - postgresql

before_install:
  - psql -c 'create database travis_ci_test;' -U postgres
  - psql -U postgres -d travis_ci_test -a -f tables.sql
  - cp local.properties.travis local.properties

script:
  - gradle install
  - gradle test
